export interface JobListing {
  id: number
  companyId: number
  companyName: string
  companyLogo: string
  companyRating: number
  companyReviews: number
  title: string
  jobType: string[]
  experienceLevel: string
  location: string
  salary?: string
  jobExpire: string
  jobHighlights: string[]
  matchScore: Array<{
    label: string
    status: "active" | "inactive"
  }>
  description: string
  responsibilities: string[]
  requirements: string[]
  applicantCount: number
  openings: number
  impressions: number
  similarJobs: Array<{
    id: number
    title: string
    company: string
    companyLogo: string
    rating: number
    reviews: number
    experience: string
    location: string
    postedDaysAgo: number
    description?: string
  }>
}

export const jobsData: Record<number, JobListing> = {
  1: {
    id: 1,
    companyId: 1,
    companyName: "FNZ Group",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.5,
    companyReviews: 200,
    title: "Front-end Developer",
    jobType: ["On-Site", "Entry Level", "Full Time"],
    experienceLevel: "8-10 Yrs",
    location: "New Baneshwor Kathmandu",
    salary: "Salary not disclosed",
    jobExpire: "3 Days, 12 Hours Remaining",
    jobHighlights: [
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
    ],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "active" },
      { label: "Location", status: "active" },
      { label: "Work Experience", status: "active" },
    ],
    description:
      "One disadvantage of Lorem ipsum is that in Latin certain letters appear more frequently than others - which creates a distinct visual impression. Moreover, in Latin only words at the beginning of sentences are capitalized. This means that Lorem ipsum cannot accurately represent, for example, German, in which all nouns are capitalized.\n\nIt sometimes makes sense to select texts containing the various letters and symbols specific to the output language.",
    responsibilities: [
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
      "Develop documentation throughout the software development life cycle (SDLC)",
    ],
    requirements: [
      "Proven experience as a .NET Developer or Application Developer",
      "Good understanding of SQL and Relational Databases",
      "Experience designing, developing and creating RESTful web services and APIs",
      "Basic know how of Agile process and practices",
      "Good understanding of object-oriented programming",
      "Good understanding of concurrent programming",
      "Sound knowledge of application architecture and design",
      "Excellent problem solving and analytical skills",
    ],
    applicantCount: 100,
    openings: 3,
    impressions: 1100,
    similarJobs: [
      {
        id: 2,
        title: "Backend Developer",
        company: "FNZ Group",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 200,
        experience: "8-10 Yrs",
        location: "New Baneshwor Kathmandu",
        postedDaysAgo: 10,
        description: "We Are Looking For A Creative And Detail-Oriented Backend Developer.....",
      },
      {
        id: 3,
        title: "Full Stack Developer",
        company: "FNZ Group",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 200,
        experience: "8-10 Yrs",
        location: "New Baneshwor Kathmandu",
        postedDaysAgo: 10,
        description: "We Are Looking For A Creative And Detail-Oriented Full Stack Developer.....",
      },
      {
        id: 4,
        title: "UI/UX Designer",
        company: "FNZ Group",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 200,
        experience: "8-10 Yrs",
        location: "New Baneshwor Kathmandu",
        postedDaysAgo: 10,
        description: "We Are Looking For A Creative And Detail-Oriented UI/UX Designer.....",
      },
    ],
  },
  2: {
    id: 2,
    companyId: 1,
    companyName: "FNZ Group",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.5,
    companyReviews: 200,
    title: "Full Stack Developer",
    jobType: ["On-Site", "Mid Level", "Full Time"],
    experienceLevel: "5-7 Yrs",
    location: "Kathmandu",
    salary: "NPR 60,000 - 80,000",
    jobExpire: "5 Days Remaining",
    jobHighlights: ["Work with modern tech stack", "Flexible working hours", "Performance bonus"],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "active" },
      { label: "Location", status: "inactive" },
      { label: "Work Experience", status: "active" },
    ],
    description: "Looking for an experienced Full Stack Developer to join our growing team.",
    responsibilities: [
      "Develop and maintain full-stack applications",
      "Collaborate with product and design teams",
      "Optimize application performance",
    ],
    requirements: [
      "5+ years of development experience",
      "Strong JavaScript/TypeScript knowledge",
      "Experience with React and Node.js",
    ],
    applicantCount: 150,
    openings: 5,
    impressions: 1500,
    similarJobs: [
      {
        id: 1,
        title: "Frontend Developer",
        company: "Tech Startup",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.3,
        reviews: 120,
        experience: "5-7 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 5,
      },
      {
        id: 2,
        title: "Backend Developer",
        company: "Tech Company",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 180,
        experience: "5-7 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 7,
      },
      {
        id: 4,
        title: "DevOps Engineer",
        company: "FNZ Group",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 200,
        experience: "5-7 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 3,
      },
    ],
  },
  3: {
    id: 3,
    companyId: 2,
    companyName: "Tech Innovations",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.6,
    companyReviews: 250,
    title: "UI/UX Designer",
    jobType: ["Remote", "Mid Level", "Full Time"],
    experienceLevel: "4-6 Yrs",
    location: "Remote",
    salary: "NPR 50,000 - 70,000",
    jobExpire: "7 Days Remaining",
    jobHighlights: ["100% Remote work", "Flexible hours", "Creative freedom"],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "active" },
      { label: "Location", status: "active" },
      { label: "Work Experience", status: "inactive" },
    ],
    description: "Join our design team to create amazing user experiences.",
    responsibilities: [
      "Design user interfaces and experiences",
      "Conduct user research",
      "Prototype and iterate designs",
    ],
    requirements: ["4+ years of design experience", "Proficiency in Figma or Adobe XD", "Strong portfolio"],
    applicantCount: 80,
    openings: 2,
    impressions: 900,
    similarJobs: [
      {
        id: 5,
        title: "Product Designer",
        company: "Design Studio",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 160,
        experience: "4-6 Yrs",
        location: "Remote",
        postedDaysAgo: 2,
      },
      {
        id: 6,
        title: "Interaction Designer",
        company: "Tech Company",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 190,
        experience: "4-6 Yrs",
        location: "Remote",
        postedDaysAgo: 4,
      },
      {
        id: 7,
        title: "UX Researcher",
        company: "Research Lab",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.3,
        reviews: 140,
        experience: "4-6 Yrs",
        location: "Remote",
        postedDaysAgo: 6,
      },
    ],
  },
  4: {
    id: 4,
    companyId: 3,
    companyName: "Data Analytics Pro",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.4,
    companyReviews: 180,
    title: "Data Analyst",
    jobType: ["Hybrid", "Entry Level", "Full Time"],
    experienceLevel: "2-4 Yrs",
    location: "Kathmandu",
    salary: "NPR 40,000 - 55,000",
    jobExpire: "4 Days Remaining",
    jobHighlights: ["Growth opportunities", "Training provided", "Team bonding events"],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "inactive" },
      { label: "Location", status: "active" },
      { label: "Work Experience", status: "active" },
    ],
    description: "Help us turn data into insights with our analytics team.",
    responsibilities: ["Analyze data and create reports", "Build dashboards", "Support business decisions with data"],
    requirements: ["2+ years in analytics or data roles", "SQL knowledge", "Proficiency in Excel or Python"],
    applicantCount: 120,
    openings: 4,
    impressions: 1200,
    similarJobs: [
      {
        id: 8,
        title: "BI Developer",
        company: "Business Solutions",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.3,
        reviews: 150,
        experience: "2-4 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 8,
      },
      {
        id: 9,
        title: "Analytics Engineer",
        company: "Analytics Hub",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 200,
        experience: "2-4 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 5,
      },
      {
        id: 10,
        title: "Data Engineer",
        company: "Data Corp",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 170,
        experience: "2-4 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 12,
      },
    ],
  },
  5: {
    id: 5,
    companyId: 1,
    companyName: "FNZ Group",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.5,
    companyReviews: 200,
    title: "DevOps Engineer",
    jobType: ["Hybrid", "Senior Level", "Full Time"],
    experienceLevel: "7-10 Yrs",
    location: "Kathmandu",
    salary: "NPR 80,000 - 120,000",
    jobExpire: "6 Days Remaining",
    jobHighlights: ["Leadership opportunities", "Mentoring junior team members", "Competitive salary"],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "active" },
      { label: "Location", status: "inactive" },
      { label: "Work Experience", status: "active" },
    ],
    description: "Lead our DevOps initiatives and infrastructure improvements.",
    responsibilities: ["Manage cloud infrastructure", "Implement CI/CD pipelines", "Monitor system performance"],
    requirements: ["7+ years DevOps experience", "AWS or GCP expertise", "Kubernetes knowledge"],
    applicantCount: 90,
    openings: 2,
    impressions: 1050,
    similarJobs: [
      {
        id: 11,
        title: "Infrastructure Engineer",
        company: "Cloud Systems",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 175,
        experience: "7-10 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 9,
      },
      {
        id: 12,
        title: "SRE Engineer",
        company: "Tech Giants",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.6,
        reviews: 220,
        experience: "7-10 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 11,
      },
      {
        id: 13,
        title: "Cloud Architect",
        company: "Cloud Experts",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 210,
        experience: "7-10 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 7,
      },
    ],
  },
  6: {
    id: 6,
    companyId: 4,
    companyName: "Mobile First Corp",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.3,
    companyReviews: 160,
    title: "Mobile App Developer",
    jobType: ["On-Site", "Mid Level", "Full Time"],
    experienceLevel: "5-7 Yrs",
    location: "Kathmandu",
    salary: "NPR 60,000 - 85,000",
    jobExpire: "2 Days Remaining",
    jobHighlights: ["Latest technologies", "International projects", "Career growth"],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "active" },
      { label: "Location", status: "active" },
      { label: "Work Experience", status: "active" },
    ],
    description: "Build cross-platform mobile applications with our talented team.",
    responsibilities: ["Develop iOS and Android apps", "Collaborate with product teams", "Optimize app performance"],
    requirements: [
      "5+ years mobile development experience",
      "React Native or Flutter expertise",
      "App Store/Play Store experience",
    ],
    applicantCount: 110,
    openings: 3,
    impressions: 1300,
    similarJobs: [
      {
        id: 14,
        title: "iOS Developer",
        company: "App Studio",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 165,
        experience: "5-7 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 3,
      },
      {
        id: 15,
        title: "Android Developer",
        company: "Mobile Solutions",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.3,
        reviews: 145,
        experience: "5-7 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 6,
      },
      {
        id: 16,
        title: "React Native Developer",
        company: "Cross Platform Dev",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 195,
        experience: "5-7 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 4,
      },
    ],
  },
  7: {
    id: 7,
    companyId: 5,
    companyName: "AI Innovations Lab",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.7,
    companyReviews: 290,
    title: "Machine Learning Engineer",
    jobType: ["Remote", "Senior Level", "Full Time"],
    experienceLevel: "6-9 Yrs",
    location: "Remote",
    salary: "NPR 90,000 - 130,000",
    jobExpire: "8 Days Remaining",
    jobHighlights: ["Cutting-edge AI projects", "Research opportunities", "Stock options"],
    matchScore: [
      { label: "Early Applicant", status: "inactive" },
      { label: "Key Skills", status: "active" },
      { label: "Location", status: "active" },
      { label: "Work Experience", status: "active" },
    ],
    description: "Work on groundbreaking AI and ML projects with our research team.",
    responsibilities: [
      "Develop ML models and algorithms",
      "Conduct research and experiments",
      "Deploy models to production",
    ],
    requirements: [
      "6+ years ML/AI experience",
      "Python and TensorFlow expertise",
      "Publications or GitHub projects preferred",
    ],
    applicantCount: 70,
    openings: 2,
    impressions: 850,
    similarJobs: [
      {
        id: 17,
        title: "AI Engineer",
        company: "AI Research Center",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.6,
        reviews: 210,
        experience: "6-9 Yrs",
        location: "Remote",
        postedDaysAgo: 1,
      },
      {
        id: 18,
        title: "Data Scientist",
        company: "Data Science Co",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 185,
        experience: "6-9 Yrs",
        location: "Remote",
        postedDaysAgo: 9,
      },
      {
        id: 19,
        title: "NLP Engineer",
        company: "Language AI",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 155,
        experience: "6-9 Yrs",
        location: "Remote",
        postedDaysAgo: 5,
      },
    ],
  },
  8: {
    id: 8,
    companyId: 2,
    companyName: "Tech Innovations",
    companyLogo: "/images/fnz-group-company-logo.jpg",
    companyRating: 4.6,
    companyReviews: 250,
    title: "Product Manager",
    jobType: ["Hybrid", "Senior Level", "Full Time"],
    experienceLevel: "8-12 Yrs",
    location: "Kathmandu",
    salary: "NPR 100,000 - 150,000",
    jobExpire: "10 Days Remaining",
    jobHighlights: ["Strategic decision making", "Team leadership", "Innovation focus"],
    matchScore: [
      { label: "Early Applicant", status: "active" },
      { label: "Key Skills", status: "inactive" },
      { label: "Location", status: "active" },
      { label: "Work Experience", status: "active" },
    ],
    description: "Lead product strategy and development for our flagship products.",
    responsibilities: ["Define product vision and roadmap", "Lead cross-functional teams", "Analyze market trends"],
    requirements: ["8+ years product management experience", "Leadership experience", "Data-driven decision making"],
    applicantCount: 60,
    openings: 1,
    impressions: 750,
    similarJobs: [
      {
        id: 20,
        title: "Senior Product Manager",
        company: "Tech Giant",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.7,
        reviews: 280,
        experience: "8-12 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 2,
      },
      {
        id: 21,
        title: "Product Owner",
        company: "Agile Tech",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.4,
        reviews: 170,
        experience: "8-12 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 8,
      },
      {
        id: 22,
        title: "Strategy Manager",
        company: "Strategic Solutions",
        companyLogo: "/images/fnz-group-company-logo.jpg",
        rating: 4.5,
        reviews: 200,
        experience: "8-12 Yrs",
        location: "Kathmandu",
        postedDaysAgo: 10,
      },
    ],
  },
}

export function getJobById(id: number): JobListing | undefined {
  return jobsData[id]
}

export function getJobsByCompanyId(companyId: number): JobListing[] {
  return Object.values(jobsData).filter((job) => job.companyId === companyId)
}

export function getAllJobs(): JobListing[] {
  return Object.values(jobsData)
}

export function getTrendingJobRoles() {
  return [
    { id: 1, name: "Full Stack Developer", jobs: 23 },
    { id: 2, name: "Frontend Developer", jobs: 18 },
    { id: 3, name: "UI/UX Designer", jobs: 12 },
    { id: 4, name: "Data Analyst", jobs: 16 },
    { id: 5, name: "DevOps Engineer", jobs: 14 },
    { id: 6, name: "Mobile App Developer", jobs: 19 },
    { id: 7, name: "Machine Learning Engineer", jobs: 11 },
    { id: 8, name: "Product Manager", jobs: 9 },
  ]
}
